version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ../app:/var/www/crud_admin
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/crud_admin
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: crud_admin
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ../mysql:/var/lib/mysql
